name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - uses: taiki-e/install-action@parse-changelog
      # - name: Generate Changelog
      #   run: parse-changelog CHANGELOG.md > ${{ github.workspace }}-CHANGELOG.md
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body_path: ${{ github.workspace }}-CHANGELOG.md
      - run: echo Released ${{ github.event.workflow_run.conclusion }}
      - run: echo Released ${{ github.event.workflow_run.head_sha }}
      - run: echo Released ${{ github.event.workflow_run.head_branch }}
      - run: echo Released ${{ github.event.workflow_run.head_commit }}
      - run: echo Released ${{ github.event.workflow_run.event }}
